django_tutorial/django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('money_tracker.urls')),
]

django_tutorial/money_tracker/urls.py
from django.urls import path
from money_tracker.views import show_tracker
from money_tracker.views import show_xml
from money_tracker.views import show_json
from money_tracker.views import show_xml_by_id, show_json_by_id
from money_tracker.views import create_transaction
from money_tracker.views import register
from money_tracker.views import login_user
from money_tracker.views import logout_user
from money_tracker.views import modify_transaction
from money_tracker.views import delete_transaction

app_name = 'money_tracker'

urlpatterns = [
    path('', show_tracker, name='show_tracker'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('create', create_transaction, name='create_transaction'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('modify/<int:id>', modify_transaction, name='modify_transaction'),
    path('delete/<int:id>', delete_transaction, name='delete_transaction'),
]

django_tutorial/money_tracker/models.py
from django.db import models

TYPE_CHOICES = [
    ('Pengeluaran', 'Pengeluaran'),
    ('Pemasukan', 'Pemasukan')
]

class TransactionRecord(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

django_tutorial/money_tracker/forms.py
from django.forms import ModelForm
from money_tracker.models import TransactionRecord

class TransactionRecordForm(ModelForm):
    class Meta:
        model = TransactionRecord
        fields = ["name", "type", "amount", "description"]

django_tutorial/money_tracker/views.py
from django.shortcuts import render
from django.shortcuts import render
from money_tracker.models import TransactionRecord
from django.http import HttpResponse
from django.core import serializers
from django.http import HttpResponseRedirect
from money_tracker.forms import TransactionRecordForm
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='money_tracker:login')
def show_tracker(request):
    transaction_data = TransactionRecord.objects.all()
    context = {
    'list_of_transactions': transaction_data,
    'name': request.user.username,
    'last_login': request.COOKIES.get('last_login')
    }
    return render(request, "tracker.html", context)

def create_transaction(request):
    form = TransactionRecordForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "create_transaction.html", context)

def show_xml(request):
    data = TransactionRecord.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = TransactionRecord.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = TransactionRecord.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = TransactionRecord.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('money_tracker:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("money_tracker:show_tracker")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response       
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('money_tracker:login'))
    response.delete_cookie('last_login')
    return response

def modify_transaction(request, id):
    # Get data berdasarkan ID
    transaction = TransactionRecord.objects.get(pk = id)

    # Set instance pada form dengan data dari transaction
    form = TransactionRecordForm(request.POST or None, instance=transaction)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "modify_transaction.html", context)

def delete_transaction(request, id):
    # Get data berdasarkan ID
    transaction = TransactionRecord.objects.get(pk = id)
    # Hapus data
    transaction.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

django_tutorial/money_tracker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Money Tracker</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

django_tutorial/money_tracker/templates/create_transaction.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{request.user.username}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'money_tracker:show_tracker' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'money_tracker:create_transaction' %}">Transaksi Baru</a>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'money_tracker:logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<h5>Tambah Transaksi Baru</h5>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Tambah"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

django_tutorial/money_tracker/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Belum mempunyai akun? <a href="{% url 'money_tracker:register' %}">Buat Akun</a>

</div>

{% endblock content %}

django_tutorial/money_tracker/templates/modify_transaction.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{request.user.username}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'money_tracker:show_tracker' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'money_tracker:create_transaction' %}">Transaksi Baru</a>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'money_tracker:logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<h5>Ubah Data Transaksi</h5>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Ubah"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

django_tutorial/money_tracker/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">

    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

django_tutorial/money_tracker/templates/tracker.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{name}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'money_tracker:show_tracker' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'money_tracker:create_transaction' %}">Transaksi Baru</a>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'money_tracker:logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<h3 class="text-center">Data Transaksi</h3>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
        <th>Nama</th>
        <th>Jenis</th>
        <th>Jumlah</th>
        <th>Tanggal</th>
        <th>Deskripsi</th>
        <th>Opsi</th>
    </tr>
  </thead>
  <tbody>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for transaction in list_of_transactions %}
    <tr>
        <td>{{transaction.name}}</td>
        <td>{{transaction.type}}</td>
        <td>{{transaction.amount}}</td>
        <td>{{transaction.date}}</td>
        <td>{{transaction.description}}</td>
        <td>
            <a href="{% url 'money_tracker:modify_transaction' transaction.pk %}">
              <button type="button" class="btn btn-warning">
                  Ubah
              </button>
            </a>
            <a href="{% url 'money_tracker:delete_transaction' transaction.pk %}">
              <button type="button" class="btn btn-danger">
                  Hapus
              </button>
            </a>
        </td>
    </tr>
  </tbody>
{% endfor %}
</table>

<h7>Sesi terakhir login: {{ last_login }}</h7>

<br>

{% endblock content %}